version: '3.1'

services:
  wordpress_students:
    image: wordpress
    restart: always
    #ports:
      #- 8080:80
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: *************
      WORDPRESS_DB_NAME: students
      WORDPRESS_DEBUG: 1
      WORDPRESS_CONFIG_EXTRA: |
        /* Multisite */
        define('WP_ALLOW_MULTISITE', true );
        define('MULTISITE', true);
        define('SUBDOMAIN_INSTALL', false);
        define('DOMAIN_CURRENT_SITE', 'website.address.com'); // TODO: change to actual domain when deploying
        define('PATH_CURRENT_SITE', '/');
        define('SITE_ID_CURRENT_SITE', 1);
        define('BLOG_ID_CURRENT_SITE', 1);
    volumes:
      - wordpress:/var/www/html
      - /root/docker/student_websites/rewrite.conf:/etc/apache2/mods-enabled/rewrite.conf
      - /root/docker/student_websites/000-default.conf:/etc/apache2/sites-enabled/000-default.conf
    networks:
      - student_wordpress

  db:
    image: linuxserver/mariadb
    restart: always
    environment:
      MYSQL_DATABASE: students
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: *************
      MYSQL_ROOT_PASSWORD: **************************
    volumes:
      - db:/config
    networks:
      - student_wordpress

volumes:
  wordpress:
  db:
networks:
  student_wordpress:
